/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post122, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/Users/home/Desktop/RadioHound_Research/Blinky/blinky.py:15" *)
(* generator = "Amaranth" *)
module top(rst, led, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [25:0] \$3 ;
  reg [24:0] \$4 ;
  reg \$5 ;
  (* src = "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/amaranth/hdl/_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "/Users/home/Desktop/RadioHound_Research/Blinky/blinky.py:18" *)
  reg [24:0] counter = 25'h0000000;
  (* src = "/Users/home/Desktop/RadioHound_Research/Blinky/blinky.py:12" *)
  output led;
  reg led = 1'h0;
  (* src = "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/amaranth/hdl/_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "/Users/home/Desktop/RadioHound_Research/Blinky/blinky.py:18" *)
  always @(posedge clk)
    counter <= \$4 ;
  (* src = "/Users/home/Desktop/RadioHound_Research/Blinky/blinky.py:12" *)
  always @(posedge clk)
    led <= \$5 ;
  assign \$1  = counter == (* src = "/Users/home/Desktop/RadioHound_Research/Blinky/blinky.py:21" *) 25'h17d783f;
  assign \$2  = ~ (* src = "/Users/home/Desktop/RadioHound_Research/Blinky/blinky.py:24" *) led;
  assign \$3  = counter + (* src = "/Users/home/Desktop/RadioHound_Research/Blinky/blinky.py:27" *) 1'h1;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$5  = led;
    if (\$1 ) begin
      \$5  = \$2 ;
    end
    if (rst) begin
      \$5  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      \$4  = 25'h0000000;
    end else begin
      \$4  = \$3 [24:0];
    end
    if (rst) begin
      \$4  = 25'h0000000;
    end
  end
endmodule
